name: mhc
description: A sample command-line application.
version: 0.0.1
repository: https://github.com/urusai88/mhc

environment:
  sdk: ^3.0.0

dependencies:
  path: ^1.0.0
  args: ^2.0.0
  yaml: ^3.0.0
  yaml_edit: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.0.0
  mhc_lints:
    path: packages/mhc_lints