name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.0

isar_version: &isar_version 4.0.0-dev.14
hive_version: &hive_version 4.0.0-dev.2

dependencies:
  path: ^1.8.0
  mhc_storage:
    path: ./../../mhc_storage
  isar: *isar_version
  isar_flutter_libs: *isar_version
  hive: *hive_version

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
