name: mhc_dev
description: A starting point for Dart libraries or applications.
version: 0.0.1

environment:
  sdk: ^3.2.0

dev_dependencies:
  test: ^1.25.0
  lints: ^3.0.0
  custom_lint: ^0.6.0
  riverpod_lint: ^2.3.0
