name: mhc_shipper
version: 0.0.1
repository: https://github.com/urusai88/mhc
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  meta: ^1.9.0
  fast_immutable_collections: ^9.1.0
  logging: ^1.2.0
  async: ^2.11.0
  state_notifier: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  mhc_lints:
    path: ./../mhc_lints