name: mhc_storage
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

isar_version: &isar_version 4.0.0-dev.14
hive_version: &hive_version 4.0.0-dev.2

dependencies:
  isar: *isar_version
  isar_flutter_libs: *isar_version
  hive: *hive_version
  flutter_secure_storage: ^9.0.0
  meta: ^1.9.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  mhc_lints:
    path: ./../mhc_lints
